### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by shdudwns** [ErkamKahriman/TNTRun#2]
18:36:34 CRITICAL > tstart에서 명령어 'tstart' 실행 중 처리되지 않은 예외가 발생했습니다: Illegal string offset 'LobbyTimer'                                                                        18:36:34 CRITICAL > ErrorException: "Illegal string offset 'LobbyTimer'" (EXCEPTION) in "plugins/TNTRun-master/src/ErkamKahriman/TNTRun" at line 247

**Comment by shdudwns** [comment]
@ErkamKahriman

**Comment by ErkamKahriman** [comment]
Thanks for reporting
